### ISSUE TITLE
pod keycloak-0 start failed

### ISSUE THREAD

**Issue by wlchn** [galexrt/kubernetes-keycloak#7]
I just run follow for test:
```
kubectl create -f . --namespace keycloak
```
pod events
```
➜  kubernetes-keycloak git:(master) ✗ kubectl describe pod keycloak-0 --namespace keycloak
Name:           keycloak-0
Namespace:      keycloak
Priority:       0
Node:           kind-control-plane/172.17.0.2
Start Time:     Wed, 04 Mar 2020 11:21:44 +0800
Labels:         app=keycloak
                controller-revision-hash=keycloak-7899c684bb
                statefulset.kubernetes.io/pod-name=keycloak-0
Annotations:    <none>
Status:         Running
IP:             10.244.0.9
Controlled By:  StatefulSet/keycloak
Containers:
  keycloak:
    Container ID:  containerd://c91d6a2bdfca218ca6db362cbfeb5dfd8aeaed48dbb489297d72964b6a3072f7
    Image:         jboss/keycloak:3.4.2.Final
    Image ID:      docker.io/jboss/keycloak@sha256:e19a31b53ad0eedcf3b6bc9731119a4077c2df63bbaef529e49c52e69cf1b55b
    Ports:         8443/TCP, 9090/TCP, 7600/TCP, 57600/TCP, 55200/UDP, 45688/UDP, 54200/UDP, 23364/TCP, 23364/UDP, 4712/TCP, 4713/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/UDP, 0/UDP, 0/UDP, 0/TCP, 0/UDP, 0/TCP, 0/TCP
    Command:
      /scripts/run.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 04 Mar 2020 12:34:14 +0800
      Finished:     Wed, 04 Mar 2020 12:34:54 +0800
    Ready:          False
    Restart Count:  25
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:      750m
      memory:   1Gi
    Liveness:   http-get http://:8080/ delay=25s timeout=1s period=7s #success=1 #failure=3
    Readiness:  http-get http://:8080/ delay=10s timeout=1s period=10s #success=2 #failure=10
    Environment Variables from:
      keycloak-env     ConfigMap  Optional: false
      keycloak-secret  Secret     Optional: false
    Environment:
      MY_POD_IP:   (v1:status.podIP)
    Mounts:
      /scripts from keycloak-scripts (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kxcxm (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  keycloak-scripts:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:      keycloak-scripts-cm
    ConfigMapOptional:  <nil>
  default-token-kxcxm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-kxcxm
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                         Message
  ----     ------     ----                   ----                         -------
  Warning  Unhealthy  33m (x41 over 69m)     kubelet, kind-control-plane  Liveness probe failed: Get http://10.244.0.9:8080/: dial tcp 10.244.0.9:8080: connect: connection refused
  Normal   Pulled     8m48s (x22 over 69m)   kubelet, kind-control-plane  Container image "jboss/keycloak:3.4.2.Final" already present on machine
  Warning  BackOff    3m37s (x236 over 66m)  kubelet, kind-control-plane  Back-off restarting failed container
```
pod logs
``` shell
➜  kubernetes-keycloak git:(master) ✗ kubectl logs -n keycloak --tail=100 -f keycloak-0
===> Failed! Hostname keycloak-0 unreachable.
=> Keycloak Hosts: 
Added user 'keycloak' to file '/opt/jboss/keycloak/standalone/configuration/mgmt-users.properties'
Added user 'keycloak' to file '/opt/jboss/keycloak/domain/configuration/mgmt-users.properties'
Added user 'keycloak' with groups null to file '/opt/jboss/keycloak/standalone/configuration/mgmt-groups.properties'
Added user 'keycloak' with groups null to file '/opt/jboss/keycloak/domain/configuration/mgmt-groups.properties'
Added 'keycloak' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
[KEYCLOAK DOCKER IMAGE] Using the external postgres database
04:21:12,031 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.1.Final
04:21:12,307 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
04:21:12,777 INFO  [org.jboss.as] (MSC service thread 1-7) WFLYSRV0049: Keycloak 3.4.2.Final (WildFly Core 3.0.8.Final) starting
04:21:13,002 INFO  [org.jboss.vfs] (MSC service thread 1-6) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
04:21:16,625 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
04:21:16,810 INFO  [org.wildfly.security] (Controller Boot Thread) ELY00001: WildFly Elytron version 1.1.6.Final
04:21:16,834 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
04:21:17,258 INFO  [org.jboss.as.patching] (MSC service thread 1-4) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
04:21:17,319 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-2) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
04:21:17,508 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
04:21:17,510 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 3.4.2.Final (WildFly Core 3.0.8.Final) started in 5455ms - Started 64 of 78 services (25 services are lazy, passive or on-demand)
The batch executed successfully
04:21:17,821 INFO  [org.jboss.as] (MSC service thread 1-7) WFLYSRV0050: Keycloak 3.4.2.Final (WildFly Core 3.0.8.Final) stopped in 18ms
04:21:20,084 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.1.Final
04:21:20,298 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
04:21:20,679 INFO  [org.jboss.as] (MSC service thread 1-7) WFLYSRV0049: Keycloak 3.4.2.Final (WildFly Core 3.0.8.Final) starting
04:21:20,947 INFO  [org.jboss.vfs] (MSC service thread 1-6) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
04:21:25,022 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/core-service=management/management-interface=http-interface' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
04:21:25,252 INFO  [org.wildfly.security] (Controller Boot Thread) ELY00001: WildFly Elytron version 1.1.6.Final
04:21:25,329 INFO  [org.jboss.as.controller.management-deprecated] (Controller Boot Thread) WFLYCTL0028: Attribute 'security-realm' in the resource at address '/subsystem=undertow/server=default-server/https-listener=https' is deprecated, and may be removed in future version. See the attribute description in the output of the read-resource-description operation to learn more about the deprecation.
04:21:26,372 INFO  [org.jboss.as.patching] (MSC service thread 1-3) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
04:21:26,431 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-5) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
04:21:26,734 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
04:21:26,737 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: Keycloak 3.4.2.Final (WildFly Core 3.0.8.Final) started in 6633ms - Started 64 of 82 services (29 services are lazy, passive or on-demand)
The batch failed with the following error: : 
WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:
Step: step-9
Operation: /subsystem=datasources/jdbc-driver=postgresql:add(driver-name=postgresql, driver-module-name=org.postgresql.jdbc, driver-xa-datasource-class-name=org.postgresql.xa.PGXADataSource)
Failure: WFLYCTL0212: Duplicate resource [
    ("subsystem" => "datasources"),
    ("jdbc-driver" => "postgresql")
]

04:21:27,233 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0050: Keycloak 3.4.2.Final (WildFly Core 3.0.8.Final) stopped in 34ms
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/jboss/keycloak

  JAVA: /usr/lib/jvm/java/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

=========================================================================

04:21:29,303 INFO  [org.jboss.modules] (main) JBoss Modules version 1.6.1.Final
04:21:30,024 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
04:21:30,314 INFO  [org.jboss.as] (MSC service thread 1-8) WFLYSRV0049: Keycloak 3.4.2.Final (WildFly Core 3.0.8.Final) starting
04:21:30,454 INFO  [org.jboss.vfs] (MSC service thread 1-8) VFS000002: Failed to clean existing content for temp file provider of type temp. Enable DEBUG level log to find what caused this
*** JBossAS process (247) received TERM signal ***
04:21:30,757 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0220: Server shutdown has been requested via an OS signal
04:21:31,072 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service jboss.as.server-controller: org.jboss.msc.service.StartException in service jboss.as.server-controller: Failed to start service
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1978) [jboss-msc-1.2.7.SP1.jar:1.2.7.SP1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_151]
Caused by: java.lang.IllegalStateException: Container is down
        at org.jboss.msc.service.ServiceContainerImpl.install(ServiceContainerImpl.java:716) [jboss-msc-1.2.7.SP1.jar:1.2.7.SP1]
        at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:223) [jboss-msc-1.2.7.SP1.jar:1.2.7.SP1]
        at org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2555) [jboss-msc-1.2.7.SP1.jar:1.2.7.SP1]
        at org.jboss.msc.service.ServiceBuilderImpl.install(ServiceBuilderImpl.java:317) [jboss-msc-1.2.7.SP1.jar:1.2.7.SP1]
        at org.jboss.as.controller.AbstractControllerService.start(AbstractControllerService.java:353)
        at org.jboss.as.server.ServerService.start(ServerService.java:296) [wildfly-server-3.0.8.Final.jar:3.0.8.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:2032) [jboss-msc-1.2.7.SP1.jar:1.2.7.SP1]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1955) [jboss-msc-1.2.7.SP1.jar:1.2.7.SP1]
        ... 3 more

java.util.concurrent.ExecutionException: Operation failed
        at org.jboss.threads.AsyncFutureTask.operationFailed(AsyncFutureTask.java:74)
        at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:268)
        at org.jboss.as.server.Main.main(Main.java:108)
        at org.jboss.modules.Module.run(Module.java:344)
        at org.jboss.modules.Main.main(Main.java:525)
Caused by: org.jboss.msc.service.StartException in service jboss.as.server-controller: Failed to start service
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1978)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Container is down
        at org.jboss.msc.service.ServiceContainerImpl.install(ServiceContainerImpl.java:716)
        at org.jboss.msc.service.ServiceTargetImpl.install(ServiceTargetImpl.java:223)
        at org.jboss.msc.service.ServiceControllerImpl$ChildServiceTarget.install(ServiceControllerImpl.java:2555)
        at org.jboss.msc.service.ServiceBuilderImpl.install(ServiceBuilderImpl.java:317)
        at org.jboss.as.controller.AbstractControllerService.start(AbstractControllerService.java:353)
        at org.jboss.as.server.ServerService.start(ServerService.java:296)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:2032)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1955)
        ... 3 more
04:21:31,099 INFO  [org.jboss.as] (MSC service thread 1-8) WFLYSRV0050: Keycloak 3.4.2.Final (WildFly Core 3.0.8.Final) stopped in 328ms
*** JBossAS process (247) received TERM signal ***
```

**Comment by galexrt** [comment]
Have you changed anything in the ConfigMaps and / or Secrets?

**Comment by wlchn** [comment]
@galexrt thanks for your reply, no, I never changed any file. I am just running first step for a test.
